language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"
#  - "3.7"
  - "nightly"

before_install:
  - sudo apt-get install g++

install:
  - pip install -r requirements.txt
  - pip install -e .

script:
  - flake8 kattischeck tests
  - pytest -v tests
